# Generated by Django 5.1.3 on 2024-12-05 15:31

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Newspaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=False,
                        force_format="WEBP",
                        help_text="Будьте уважні, зображення буде масштабовано автоматично",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1080, 1080],
                        upload_to="news_images/",
                    ),
                ),
                (
                    "redactor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newspapers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(related_name="newspapers", to="news.topic"),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
