# Generated by Django 5.1.3 on 2024-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="newspaper",
            name="topic",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topic",
            field=models.ManyToManyField(related_name="newspapers", to="news.topic"),
        ),
    ]
