# Generated by Django 5.1.3 on 2024-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/no-avatar.png",
                upload_to="profile_images/",
            ),
        ),
    ]
